name: fuse_wallet_sdk
description: Fuse Wallet SDK now has a Dart implementation, making it even
  easier to integrate blockchain technology into your mobile apps.
version: 0.3.3
homepage: https://fuse.io/sdk
repository: https://github.com/fuseio/fuse_wallet_sdk

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  centrifuge: ^0.14.0
  compute: ^1.0.2
  data_channel: ^2.0.0+1
  decimal: ^2.3.3
  dio: ^5.4.3+1
  freezed_annotation: ^2.4.1
  hex: ^0.2.0
  http: ^1.2.1
  json_annotation: ^4.9.0
  synchronized: ^3.1.0+1
  userop: ^0.2.0
  web3dart: ^2.7.3

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.25.4
