name: fuse_wallet_sdk
description: Fuse Wallet SDK now has a Dart implementation, making it even
  easier to integrate blockchain technology into your mobile apps.
version: 0.3.6
homepage: https://fuse.io/sdk
repository: https://github.com/fuseio/fuse_wallet_sdk

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  centrifuge: ^0.14.0
  compute: ^1.0.2
  data_channel: ^2.0.0+1
  decimal: ^3.0.2
  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  hex: ^0.2.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  synchronized: ^3.2.0
  userop: ^0.3.0
  web3dart: ^2.7.3

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.8
