name: charge_smart_wallets_sdk
description: SDK for Charge Smart Wallet API
version: 0.0.1
homepage: https://chargeweb3.com/
repository: https://github.com/fuseio/charge_wallet_sdk

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  centrifuge: ^0.9.2
  compute: ^1.0.2
  data_channel: ^2.0.0+1
  decimal: ^2.3.2
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  gql: ^0.14.0
  graphql: ^5.1.3
  hex: ^0.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  path: ^1.8.2
  retrofit: ^3.3.1
  web3dart: ^2.5.2

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.0
  test: ^1.22.0
